# permissions for end users to edit namespaceresourcereports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceresourcereport-editor-role
rules:
- apiGroups:
  - cloud.dancingcode.cn
  resources:
  - namespaceresourcereports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.dancingcode.cn
  resources:
  - namespaceresourcereports/status
  verbs:
  - get
