# permissions for end users to view namespaceresourcereports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaceresourcereport-viewer-role
rules:
- apiGroups:
  - cloud.dancingcode.cn
  resources:
  - namespaceresourcereports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.dancingcode.cn
  resources:
  - namespaceresourcereports/status
  verbs:
  - get
